# Match original prompt: green path + git status + white $
format = """
[](green)$directory\
$git_branch\
$git_status\
[](white) \\$ """

[directory]
style = "green"
format = "[$path]($style)"
truncation_length = 100
truncate_to_repo = false

[git_branch]
style = "white"
format = " on [$branch]($style)"

[git_status]
style = "white"
format = '([\[$all_status$ahead_behind\]]($style))'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕${ahead_count}⇣${behind_count}"
untracked = "?"
stashed = "\\$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[character]
disabled = true

